### ISSUE TITLE
please add a licese

### ISSUE THREAD

**Issue by barrybecker4** [pmneila/jsexp#4]
P, I really like this project, but noticed that it has not license.  It would be great is this project could adopt some sort of open-source license so that others would feel to free to continue the work that you have started.
thanks,
Barry

**Comment by pmneila** [comment]
Hi,

Feel free to use this project however you want. Just to make that point clear (and also because you asked :) ), I have licensed the project under the modified BSD license (aka the BSD 3-clause license).

**Comment by barrybecker4** [comment]
Perfect. Thanks!
