### ISSUE TITLE
what's the palette for this image?

### ISSUE THREAD

**Issue by zemora** [pmneila/jsexp#8]
Hi pmneila: what's the palette and pattern for [this image](https://github.com/pmneila/jsexp/raw/master/grayscott/snapshots/spotsx.png)? I can not reproduce it ...

**Comment by pmneila** [comment]
I don't have the exact configuration I used in that image, but it was very close to this:

0.018,0.051,0.06060606060606061,#000000,0.12878787878787878,#3B49FF,0.15151515151515152,#FFFFFF,0.18181818181818182,#3B49FF,0.22727272727272727,#000000

Paste that in the Share box of the simulation and press enter.

**Comment by zemora** [comment]
thanks! It works.
